### ISSUE TITLE
ImportError: cannot import name neo4j

### ISSUE THREAD

**Issue by FrostyX** [technige/py2neo#253]
Hi, I have installed `py2neo` using

```
pip install py2neo
```

Then I have tried some basic example, but I cant even import `neo4j` class.

My python code:

```
#!/usr/bin/python
from py2neo import neo4j
graph_db = neo4j.GraphDatabaseService("http://localhost:7474/db/data/")
```

Throws

```
Traceback (most recent call last):
  File "./py2neo.py", line 3, in <module>
    from py2neo import neo4j
  File "/home/frostyx/graphs/py2neo.py", line 3, in <module>
    from py2neo import neo4j
ImportError: cannot import name neo4j
```

**Comment by saran001** [comment]
Hi I have installed py2neo using 
`sudo pip install py2neo`

After that i wrote a code and saved the file as  'saran.py'

`from py2neo import neo4j, authenticate, Graph

host_port = "localhost:7474"
user_name = "neo4j"
password = "saran_probyto2425"

authenticate(host_port, user_name, password)
graph = Graph("http://localhost:7474/db/data/")
`

But I'm getting an error message as:
`Traceback (most recent call last):
  File "saran.py", line 1, in <module>
    from py2neo import neo4j, authenticate, Graph
ImportError: cannot import name neo4j
`
I don't know what the problem is.Could you please help me?

**Comment by mkoertgen** [comment]
Having the same problem. Using python 3 on Windows

**Comment by nigelsmall** [comment]
You're installing py2neo 3 and using code for py2neo 2. The `neo4j` module no longer exists in v3. Compare the two sets of docs here:

http://py2neo.org/2.0/
http://py2neo.org/v3/

**Comment by ElnazBigdeli** [comment]
I have installed py2neo I am just running these three lines. It has problem with instantiating the graph.
from py2neo import Graph 
from py2neo import Node, Relationship
graph = Graph()


the error is this : SocketError: Unknown error

that I believe is with port problem. 
More detail : my python is 2.7 running on windows 8.
