### ISSUE TITLE
CreateRelationship not implemented correctly?

### ISSUE THREAD

**Issue by jsw883** [technige/py2neo#405]
Hi Guys, I just wanted to draw your attention to the fact that `py2neo.cypher.CreateRelationship` is not implemented correctly, suffering from a copy + paste from `py2neo.cypher.CreateNode` without any additional implementation (even the parameter names mismatch, confusing type / label). Are you going to implement a fully capable `CreateRelationship` in the future? I could do it for you with a little bit more reading into CypehrWriter, if your hands are full.

**Comment by nigelsmall** [comment]
Due to time constraints, this will be implemented correctly in a future version but not the next point release. For now, it will be removed.

**Comment by jsw883** [comment]
I have a fairly comprehensive CreateRelationship function written, which creates the relationship only, matching nodes that exist in the graph already. I would need to tweak this to use your CypherWriter (rather than hard coding the cypher in the class) and to allow either matching / creation of the nodes. This could be done using a parameter to specify (a) node creation (unless it would violate uniqueness constraints), (b) node matching, or (c) node **merging** (which ispossibly the most useful, but would require specifying the primary properties to match on, and other properties that could be merged). Do you have any preference for the implementation? If so, I am happy to write it up and submit a pull request, if you want it done now (point release, as opposed to the next version).

**Comment by nigelsmall** [comment]
That would be great. In terms of node creation vs matching, my plan for the CypherTask implementations is to have one for each specific task, rather than trying to make a task too general. Also, having a parameter switch for functionality can lead to a less intuitive API. Therefore separate classes (perhaps `CreateRelationship` and `CreateRelatedNodes`) would be my preferred choice. There could then be further classes such as `MergeRelatedNodes` or `CreateUniqueRelationship` (using a Cypher `CREATE UNIQUE` clause).

I'd be very happy to review a PR with one or more of these (perhaps a single PR for each would be best?) assuming you have time.

Thanks :-)
