### ISSUE TITLE
How should I use py2neo in a web app?

### ISSUE THREAD

**Issue by realmhamdy** [technige/py2neo#444]
I started using py2neo expecting there's a JSON serialization for neo4j's responses somewhere, but I can't find it and I'm surprised that it's like I'm the only one asking this very basic question.

When I make a query like this:

```
graph.cypher.execute("MATCH (n) return n;")
```

With possibly many node types returned. How should I bend the undocumented `RecordList` to my will?

**Comment by nigelsmall** [comment]
I'm not sure what you're asking. There's no such thing as a node "type" and though the `RecordList` could possibly do with some clarification in the docs, it's only really a list of `Record` objects, nothing more.

Can you elaborate?

**Comment by github-account-because-they-want-it** [comment]
Sorry for being late. Here's more explanation to what I saw as an issue.
The type of data returned from the text-based query above is a `RecordList`, which is more of expected from py2neo's object-graph mapping. I expected a JSON output there instead, or at least a serializer for `RecordList` like [serializing django's ORM objects](https://docs.djangoproject.com/en/1.8/topics/serialization/).

I don't think this belongs here, but how do I change the label (type) of a relationship?
setting the type value directly on a bound relationship raises:
```
my_rel.type = "new type"
AttributeError("The type of a bound Rel is immutable")
```
Going through the routine of:
1- unbinding
2- setting the new value,
3- rebinding to the relationship uri
4- pushing from the graph
doesn't raise but doesn't update the type either.

**Comment by github-account-because-they-want-it** [comment]
I think I found how to translate [this SO answer](http://stackoverflow.com/a/22670791/4459766) to py2neo:
```
new_label = "new label"
old_rel = graph.relationship(old_rel_id)
graph.create(Relationship(old_rel.start_node, new_label, old_rel.end_node))
graph.delete(old_rel)
```

**Comment by ajendrex** [comment]
Hello,
I'm also getting a recordlist from a cypher query and then I want to serialize and save it to a session variable for further use. So I'm also wondering what would be the recommended way of accomplishing this.

greetings,
Hector.
