### ISSUE TITLE
py2neo.graph.create() error with Relationship subgraph

### ISSUE THREAD

**Issue by eoghancunneen** [technige/py2neo#547]
Hi Nigel,
I have a reproducible bug relating to the creation of N relationships between two nodes. Please see the snippet below:

This is py2neo v3.1.1:

```
import py2neo
from_node = py2neo.Node("FROM_NODE", "TEST", test=True, value='Source')
to_node = py2neo.Node("TO_NODE", "TEST", test=True, value='Destination')

# Create the graph instance:
GRAPH = py2neo.Graph("http://localhost:7474/db/data")
GRAPH.create(from_node)
GRAPH.create(to_node)

# Create a list of properties, in this case it's just {'number': N}. We'll use N=4:
properties = [dict(number=d) for d in range(4)]

# eg:
# print properties
# [{'number': 0}, {'number': 1}, {'number': 2}, {'number': 3}]

# Iterate over the properties and create a new relationship between the two nodes:
for p in properties:
    rel = py2neo.Relationship(from_node, "TRAVELS_TO", to_node,  **p)
    GRAPH.create(rel)
```

What I would expect to see is 4 unique relationships between the FROM_NODE and the TO_NODE, instead, the `graph.create(rel)` call seems to update the properties on the existing 1 relationship. What I'm left with is 1 relationship with the [-1]th property. In this case `{number: 3}`. It seems to act like a `merge()` call, rather than a `create()`?

Is this a bug, or is there another process I should carry out to create these unique relationships?

Many thanks,
Eoghan

**Comment by nigelsmall** [comment]
Hi Eoghan

The higher-level API operations and graphy types provided by py2neo have this limitation by design. That is: multiple relationships of the same type between the same node pair are not supported. There is a note in the docs to this effect but I've just noticed it's not in the most obvious place (http://py2neo.org/v3/types.html#Relationship, hidden in the equality description).

To do what you are trying to do, you'll have to drop down into Cypher for now. I have a vague idea floating around in my head about allowing this via relationship "collections" or similar but that's a bit off in the future somewhere, so for now Cypher is your friend.

Nigel

**Comment by eoghancunneen** [comment]
Got it - thanks Nigel.
I go back to Cypher to execute what I need and post back the solution should people find it useful. For what it's worth, the concept of relationship "collections" makes sense.
Appreciate the response.
Best,
Eoghan
