### ISSUE TITLE
Server closed connection when using Bolt

### ISSUE THREAD

**Issue by john-bodley** [technige/py2neo#618]
Per this Stack Overflow [post](http://stackoverflow.com/questions/41622019/py2neo-protocolerror-server-closed-connection-when-using-bolt), when using the Bolt protocol I've seen examples of the server closing the connection possibly due to a timeout, however I've been unable to find any timeout related information for the Bolt protocol.

Note our previous workaround was to use the HTTP protocol, however it seems like the HTTP protocol doesn't stream when fetching data like Bolt, and thus we're running into memory issues.

**Comment by heidricha** [comment]
Same issue here. Method:

python code:
  create docker container for neo4j: test-neo
  wait for being ready
  connect test-neo: g
  use g
  drop docker container: test-neo
  create docker container for neo4j: test-neo (yes, exactly the same as for the first time)
  wait for being ready
  connect test-neo: g
ERROR: Server closed connection (neo4j is OK otherwise, http and bolt ports are tested)

Going fwd, if we drop/create the container again, next time the connection will be OK, and later on, every second container will be usable.

Creating different IP address for the containers helps, exiting python interpreter helps. Seems like the problem is caused by loosing the neo4j server on IP:port, and finding there another one.

Is there a way to reset (unload/load) the py2neo module completely?

**Comment by technige** [comment]
Neither server nor client contain code to time out connections. Such disconnections are usually the result of third party network infrastructure that is attempting to close connections it perceives as idle.

The second issue here is unrelated and most likely due to the connection pool being unaware of the machine behind the IP address having been stopped and restarted. Docker network events don't always manifest in the same way as real network events and much of the underlying code was written before Docker became widespread.

My recommendation is to invoke the `Database.forget_all()` method which will drop all internal connector objects, thereby allowing new ones to be recreated.
