### ISSUE TITLE
py2neo 4.0 doc out of date

### ISSUE THREAD

**Issue by MiracleYoung** [technige/py2neo#679]
Hi boss,

I find that doc v3 and v4 is out of date, so that I can not successfully learn py2neo and hard to check what's wrong there.

Could you please improve the Doc if you feel possible to do that...

Regards.

**Comment by technige** [comment]
The docs have been updated for both the versions you mention, so I'm not sure what you are looking at that you feel is out of date.

**Comment by MiracleYoung** [comment]
> The docs have been updated for both the versions you mention, so I'm not sure what you are looking at that you feel is out of date.

I use py2neo 4.x and 3.x their API does not look like docs....some functions not exist in these versions....

**Comment by technige** [comment]
Specifically...?

**Comment by tpanza** [comment]
@technige Not sure if this would be better addressed as a separate issue, but here are some potential doc issues:

The [documentation for `subgraph.nodes()`](https://py2neo.org/v4/data.html#py2neo.data.Subgraph.subgraph.nodes) implies that `nodes` is callable function due to the `()` at the end.

If `.nodes()` is used like this, it raises this:
`TypeError: 'SetView' object is not callable`

A similar issue exists for `subgraph.relationships` and `subgraph.labels`. These are also SetView objects, rather than functions.

However, `subgraph.keys()` and `subgraph.types()` *are* callable.

Looking at [the code](https://github.com/technige/py2neo/blob/v4/py2neo/data.py#L635), this is probably due to the `@property` decorator for `nodes`, `relationships`, and `labels`, whereas `keys()` and `types()` do *not* have this decorator.

So either the code would need to be changed (remove the `@property` decorators) so that `nodes`, `relationships`, and `labels` behave the way the docs say, or the docs would need to be updated to indicate that `nodes`, `relationships`, and `labels` are properties, not functions.

I'm guessing the doc update would be less risk
