### ISSUE TITLE
primary_key=None not allowed in merge?

### ISSUE THREAD

**Issue by TomGroves** [technige/py2neo#695]
I can't perform a simple relationship MERGE, because tx.merge seems to require a primary_key, but my very simple relationship doesn't have any properties to match on.
```
rel=py2neo.Relationship(f,"sightedAt",sighting)
tx.merge(rel,primary_label="sightedAt",primary_key=None)
```
throws 
> ValueError: Primary label and primary key are required for MERGE operation

I think a lot more examples of the use of MERGE are needed in the docs - its behaviour seems very different from Cypher's MERGE. How can we merge an entire subgraph if we have to specify a single label and property to match on? Surely it should match on _every_ label and propertyon the subgraph, like Cypher's MERGE?

**Comment by bramson** [comment]
I give the following comment: I think a lot more examples of the use of MERGE are needed in the docs" one thousand thumbs up.  There is basically no instruction on how to get anything done with py2neo, so no matter how powerful it may be it's completely worthless if nobody can figure out how to use it because there is no real documentation.  I am also just trying to do a simple merge, and it fails even when I try to provide a primary label and key...and of the few examples of using merge available on Stack Exchange, most of them DON'T EVEN INCLUDE THESE!!!  So I have no idea how to perform this basic operation and there is no assistance available anywhere.

**Comment by bwmetz** [comment]
I'm new to py2neo as well, but multiple call outs like this and my own experience show that MERGE in py2neo is nowhere near as flexible as a CYPHER query.  I've resorted to doing all things complicated by running CYPHER queries.  This has the added benefit of being able to test them first using the Neo4j browser on sample data, then using them in combination with more simple operations using "native" py2neo calls.
