### ISSUE TITLE
how to create relationship between existing nodes

### ISSUE THREAD

**Issue by statfs** [technige/py2neo#777]
This is a simple code, 2 node and 1 relation. 
It should be 2 node, but 4 node finally created, which means another two nodes created wrongly. 
Just see the picture below.
![image](https://user-images.githubusercontent.com/9411067/71305226-6242b300-240b-11ea-9b6b-a8381900b827.png)

Please figure out the wrong step and tell me the right way to create relationship between this two existing nodes. Thank you very much.

```
from py2neo import Graph, Node, Relationship, NodeMatcher
graph = Graph('http://localhost:7474',username='neo4j',password='neo4j')
graph.delete_all()
data = {"id1":"name1", "id2":"name2"}
for id, name in data.items():
  node = Node("People", id = id, name = name)
  graph.create(node)

mapping = {"id1":"id2"}
for id1, id2 in mapping.items():
    cql1 = "match(n:People {id: \"" + id1 + "\"}) return n limit 1"
    cql2 = "match(n:People {id: \"" + id2 + "\"}) return n limit 1"
    leftNode = graph.run(cql1)
    for left in leftNode:
        rightNode = graph.run(cql2)
        for right in rightNode:
            relation = Relationship(left, "to", right)
            graph.create(relation)
```

**Comment by technige** [comment]
You're mixing high-level API (such as `graph.create`) and lower level Cypher calls in your code, which isn't an intended approach. Also, I'm uncertain why you're re-querying the database for the nodes to build the relationship.

You can quite simply create two nodes and relationship with something like this:
```
>>> g = Graph("http://localhost:7474", auth=("neo4j", "password"))
>>> a = Node("Person", name="Alice")
>>> b = Node("Person", name="Bob")
>>> ab = Relationship(a, "KNOWS", b)
>>> g.create(ab)
```

Please note though that this issue list is intended for bug reports rather than general support questions, and as such I cannot guarantee a reply here. Please look to StackOverflow or the Neo4j community forum for that instead.

**Comment by KB5201314** [comment]
This problem is still exists in latest version(5.0b1) of py2neo.

The code you show is to create two Nodes and immediately create a relationship between them. It works fine but I am looking for a way to create relationship between two **existing nodes*. 
I noticed that if I use the `graph.nodes.match()` function to get the nodes, and then create a relationship between them, I will get two other new nodes with no label on them.

The code is here:
```python3
# a and b are two existing nodes
a = graph.nodes.match("Person", name="Alice")
b = graph.nodes.match("Person", name="Bob")
ab = Relationship(a, "KNOWS", b)
graph.create(ab)
```
It should be equivalent to the following code
```
MATCH (a:Person),(b:Person)
WHERE a.name = 'Alice' AND b.name = 'Bob'
CREATE r=(a)-[:KNOWN]->(b)
RETURN r
```

Before execute:
![image](https://user-images.githubusercontent.com/14936301/83506656-09b72c00-a4fa-11ea-81bc-7a467b6e3723.png)

Expected:
![image](https://user-images.githubusercontent.com/14936301/83506725-1e93bf80-a4fa-11ea-9d36-00290051a3fe.png)

However, after executing it, I got two new Nodes with all properties but no label on them:
![image](https://user-images.githubusercontent.com/14936301/83506792-379c7080-a4fa-11ea-8a94-c4a4b04d038e.png)

Is this a bug, or am I misunderstood?

**Comment by KB5201314** [comment]
> @technige @KB5201314 I too get the same issue. Did you get a solution for the same?

It has been a long time since I faced this problem. I'm not sure whether it has been fixed now.
To bypass this bug, I gave up using these API but using `graph.run()` and lower level cypher string instead

```python
def insert_relation():
    # Owns
    cypher = '''
        MATCH (a:Player{{steamid:'{}'}}),(b:Game{{appid:{}}})
        CREATE r=(a)-[:Owned]->(b)
    '''
    for owned_games in all_owned_games:
        if 'games' in owned_games:
            for g in owned_games['games']:
                graph.run(cypher.format(owned_games['_id'], g['appid']))
```
https://github.com/KB5201314/steam-spider/blob/44ec37b36821a3b7478fd306e50bc4dff46f3092/build_kg_into_neo4j.py#L74-L83

**Comment by technige** [comment]
Replying to a closed issue is unwise. This doesn't generally get noticed. Please raise a new issue if you see a problem, potentially linking to an existing issue, if relevant.

In this case @KB5201314, you were using the API wrong. I assume you intended for the `graph.nodes.match("Person", name="Alice")` code to return a node into `a`. It does not. It returns a `NodeMatch` object which can be iterated over to yield any nodes which match that pattern. If you want to select _one_ of these matches only, you will need to append `.first()`, which will then return the first matched node discovered.

This means that your code `Relationship(a, "KNOWS", b)` is broken, since this is not forming a relationship between two nodes.

**Comment by technige** [comment]
@YojanaGadiya What is your problem specifially? Can you raise this in a new issue, please, rather than tagging onto the end of a closed issue.

**Comment by YojanaGadiya** [comment]
> @YojanaGadiya What is your problem specifially? Can you raise this in a new issue, please, rather than tagging onto the end of a closed issue.

@technige the issue seems to be solved with the above explanation. Sorry for replying in a closed issue.

**Comment by technige** [comment]
OK, no problem.
