### ISSUE TITLE
Implement best practices for graph deletion

### ISSUE THREAD

**Issue by mcsoini** [technige/py2neo#797]
`Graph.delete_all` just runs `MATCH (a) DETACH DELETE a`, which is likely to cause issues even for moderate sized graphs (x*10**5 nodes). Would it make sense to implement the best practices as listed under the following link? https://neo4j.com/developer/kb/large-delete-transaction-best-practices-in-neo4j/

Would it be an option to try running `apoc.periodic.iterate("MATCH` and fall back to something non-apoc in case it fails due to apoc not being installed?

**Comment by technige** [comment]
I can see the argument here, and I am sympathetic, but this really isn't a problem for py2neo to solve. Instead it is something to be fixed within Neo4j itself.

Of the methods listed, server-side clearance of the file system directory isn't an option (this is a remote client) and py2neo doesn't (yet?) contain any recognition of APOC. Batch deletion of N entities at a time is also hard to tune for the general case.

I currently instead see this as something to be implemented by the client application itself, which has better knowledge of the data model, and can delete appropriately. But perhaps, ultimately, lobbying Neo4j* to improve the performance of bulk deletes in general is absolutely critical.

(*Speaking here purely as a community library author, rather than as a Neo4j employee)

So, closing this as a `wontfix`.
