### ISSUE TITLE
Inverse Labels

### ISSUE THREAD

**Issue by usbader** [technige/py2neo#842]
Hello all, 

I searched on github and StackOverflow about how I can make inverse labels on one relationship. I know that having a bidirectional relationship is not recommended in Neo4j, so I wonder if it is a future feature or something that is already implemented. I want to create something like the following. 

(MIT:Acronym)-[:IsExpandedTo]->(Massachusetts Institute of Technology:Term)
I want to add an inverse label to the relationship such as IsAbbreviatedAs.

**Comment by technige** [comment]
Relationships have a single type (not a label, since this is an attribute of nodes) and a direction. The type does not apply to the direction per se. Therefore, what you are asking for does not exist.

The correct way to think about relationship types is as an identifier that can be used to group relationships of a similar kind. Often, while that relationship type will bear some resemblance to how the relationship is surfaced in your application, this is not strictly required.

For example, you might have `(Charles:Person)-[:MOTHER]->(Elizabeth:Person)`. This relationship is stored internally as three entities: two nodes and a relationship connecting those nodes. This relationship has a type (called `MOTHER`) which when read aloud, makes sense in one direction only. However, you could equally well decide to name that relationship type `CHILD_MOTHER` or even `MOTHER_CHILD` if the direction were reversed. Or if you weren't using English, maybe it would be `MUTTER` or `MÈRE`. All of these options would represent identical semantics within your model, and would likely use exactly the same internal ID within the data store to represent the relationship type.

What is important is how you then use that data. You can infer that `(a)-[:MOTHER]->(b)` means that both `a` is the child of `b` and `b` is the mother of `a`. You don't need to store extra information in your data model to know that. And your queries and client applications can also use this logic.

So for these reasons, such a feature is not necessary, and is thus not on the roadmap.
