### ISSUE TITLE
py2neo.wiring.WireError: Broken

### ISSUE THREAD

**Issue by zhangyukuo** [technige/py2neo#844]
When i run the program in a timed task, this problem occurred. I use flask_apscheduler and py2neo, hoping to update the data in an hour. But this error will happen every once in a while. I don't know how this error is caused. Who knows can tell me what is going on. Thank you very much!

**Comment by canihavesomecoffee** [comment]
I've seen this error pop up when the connection between py2neo and the underlying neo4j database is dropped/killed.

**Comment by quentinfayet** [comment]
Same here, I happen to have this error once a while. It does not seems to be related to a dropped/killed connection in my case though.

**Comment by himalayoza** [comment]
I posted a new issue on the same topic. I have explained the scenario in detail. Basically I am running a large data ingestion script. After close to 75 min or so of running the script I get this WireError. I do not see any errors in Neo4j server logs. This leads me to believe that the issue is on Py2Neo side.

After going through Py2Neo code I am uncertain under what circumstances the connection to Neo4J server is closed, if there are buffer issues or some other issues.

**Comment by adn201** [comment]
same here and the product is almost in production :(, I reported this since some months ago
 WireError("Broken")

**Comment by zhangyukuo** [comment]
My project is built by flask+pymsql+py2neo+flask_apschedulers.  Pymsql does not seem to be suitable for production. In other forums, some people say that when pysqml is in production, there will be link timeout errors from time to time. I guess it’s because of this error of pymysql that leads to WireError("Broken"). I will try other database interactive tools, such as Flask-SQLAlchemy. If you have other ideas, welcome to share

**Comment by haerbinwyzhaha** [comment]
same situation..

**Comment by technige** [comment]
Unfortunately, vague descriptions of connectivity errors will be almost impossible for me to diagnose. Descriptions of the network context, and the code that's running might help a bit, but it's definitely impossible for me to do much without.

The Wire class is really just a simple socket wrapper with buffering. There's very little in there to go wrong, and "broken" simply indicates the socket has been closed from "elsewhere" - i.e. either the remote server or the network. Given that Neo4j itself never terminates connections in the middle of running something, it's most likely to be something else killing these.

Please add a :+1: to this comment if your connection dies primarily or solely when executing long-running queries. Comments on how long it runs before failure will be useful, and descriptions of the network environment as well.

**Comment by adn201** [comment]
Hi I think the issues can be many that can be causing the network connection issues, but still the py2neo is not doing a proper job. I was using Java for many years almost 13 and all the drivers handle this type of errors by their own, the user does not need to catch this errors and try to reconnect himself, I think this will be a really good improvement but I would say a need, that py2neo try more than one time to re-connect and dont make the final user deal with this types of errors, now if the py2neo cannot connect again lets say in 3 attemps then they can throw these exceptions, but most of the time, when I was retrying I could connect without issues. But that issue cause me to modify all may data access, and this is wrong as should not be in the user layers but in py2neo layers.

thanks

**Comment by adn201** [comment]
i think in the pool you are using connections that are not valid any more for some reason, I think, and please add the functionality to drop this connection and create a new one and then retry. that will help us a lot !!

**Comment by technige** [comment]
If it were a simple case of picking up a new connection and trying again on failure, that functionality would have been added ages ago. But it isn't. On top of that, py2neo has never pretended to be a tool for use in complex network environments (i.e. those with more that just a single client and server); if connections are being killed, this is almost always down to some third party component taking action with no context of the work in progress.

Why isn't it simple? Firstly because there are many points at which disconnection can occur:
1. An initial failure to connect is the simplest case. Then, trying again might work.
2. Disconnection while idle. This generally wouldn't cause any challenge with reconnection either.
3. Disconnection between queries within a transaction. Much harder to retry - the entire transaction would need to start again.
4. Disconnection while running a query. Similar to above.

And then how should retry work? Find another connection? To the same server or a different server? Immediately, or after a delay? If after a delay, should the delay increase exponentially? After how long should it give up? After a certain number of attempts? After a certain time limit has passed? And then what? The user could still see a failure, unless we're happy entering an infinite loop of retries.

How does the driver know the difference between a server being unavailable temporarily (network glitch) or permanently (DBMS shutdown)? How does the driver know when there's an alternative server available but the original server is never coming back?

It doesn't. And none of these questions are straightforward to answer. Even implementing a simple default retry behaviour would work for maybe 20% of users, but would likely cause other issues for other users.

Ultimately, it all comes back to the point that py2neo was only ever designed for simple client-to-server interaction. It's a hobby project; I work on it in my spare time. Right now, anything more complex is down to the user to manage.

That said, I will continue to try to improve diagnostic capabilities over time. I am adding experimental routing support, and have made some progress in implementing retries in certain circumstances. But there's no quick fix, and the user will _always_ have to take responsibility for the components in their network to some extent.

**Comment by adn201** [comment]
Hi thanks for your reply,

I think what you are mentioning is trying to overcomplicate the stuff, yes a  retry mechanism is one of the best to do, because for the final user is a real problem that he is losing transactions because an issue with the connection that is too simple. I don't see that adding a mechanism to retry is that big deal at all !!! and I really see that you keep connections in the pool that are already close and you try to use then becasue is close because lets say the DB got rebooted, you dont detect that and then you return that connection to the user, which all this issues could be avoided. To me the issue did not happen when running a query is always that a connections is lose, the problem is simple you are still trying to use that connection and that is definitely upt to the library.


 "How does the driver know the difference between a server being unavailable temporarily (network glitch) or permanently (DBMS shutdown)? How does the driver know when there's an alternative server available but the original server is never coming back?"

that does not really matters, what matters is you lose a connection, just retry to open or simple dont return this to the user. 
many drivers already deal with this issue, in Java, you could take a look on the JDBC it is a common issue.

but the answer to all of this is this one:

It's a hobby project; I work on it in my spare time.

then please delete from the neo4j page dont allow them to put in there because the library is a joke then and should not be considered seriously just for students or small projects. I read that you mention that in your library but neo4j should add that as well, this should not be in any case used for something serious and you are not mentioning that, that this library is not for serious projects, otherwise you are making lose time to the final user with just a simple answer "It's a hobby project; I work on it in my spare time."

which is not nice from your side.

thanks

**Comment by adn201** [comment]
Yes actually we are changing to the official driver just I want to avoid people be on the same situation than me. and sorry my intention was not to bother you or make you up set, but as well your answer is not professional at all:

"Ultimately, it all comes back to the point that py2neo was only ever designed for simple client-to-server interaction. It's a hobby project; I work on it in my spare time."

I never wait for those excuses.

Have a great Day, and try to be clear in the neo4j offical web page I think it will be fair.

thank you !! anyway I think the library should be good for other type of contexts.

**Comment by belean** [comment]
I was having this problem too but solved it with the easy workaround of using https:// instead of bolt://!
